### register user
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "username": "admin",
  "email":"admin@email.com",
  "password": "adminpw"
}

### register user
POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "username": "user",
  "email":"user@email.com",
  "password": "userpw"
}


### login user
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "admin@email.com",
  "password": "newadminpw"
}

### login user
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "user@email.com",
  "password": "userpw"
}


### get user info
GET http://localhost:3000/api/v1/auth/user/2

### verify email
GET http://localhost:3000/api/v1/auth/verify?token=3ed739a0-8552-486f-bc8f-a258ee013754


### forgot password
POST http://localhost:3000/api/v1/auth/forgot-password
Content-Type: application/json

{
  "email": "admin@email.com"
}

### reset password
POST http://localhost:3000/api/v1/auth/reset-password?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImlhdCI6MTcwMDgyNTgwMywiZXhwIjoxNzAwODI2MTAzfQ.1PNkGhSSRqwT-VKzpHQz-P_VUxv3ykehSUSnCWJ0QIs
Content-Type: application/json

{
  "newPassword": "newadminpw"
}

### logout
GET http://localhost:3000/api/v1/auth/logout
